//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DenunciasSolicitudValoraciones
    {
        public int id { get; set; }
        public int id_solicitud_valoracion { get; set; }
        public int id_usuario { get; set; }
        public int motivo { get; set; }
        public Nullable<System.DateTime> fecha_denuncia { get; set; }
        public string descripcion { get; set; }
    
        public virtual Denuncias Denuncias { get; set; }
        public virtual SolicitudValoraciones SolicitudValoraciones { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
