//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Denuncias
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Denuncias()
        {
            this.DenunciasRecomendaciones = new HashSet<DenunciasRecomendaciones>();
            this.DenunciasSolicitudRecomendaciones = new HashSet<DenunciasSolicitudRecomendaciones>();
            this.DenunciasSolicitudValoraciones = new HashSet<DenunciasSolicitudValoraciones>();
            this.DenunciasValoraciones = new HashSet<DenunciasValoraciones>();
        }
    
        public int id { get; set; }
        public int motivo { get; set; }
        public Nullable<int> reputacion_descontada { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DenunciasRecomendaciones> DenunciasRecomendaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DenunciasSolicitudRecomendaciones> DenunciasSolicitudRecomendaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DenunciasSolicitudValoraciones> DenunciasSolicitudValoraciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DenunciasValoraciones> DenunciasValoraciones { get; set; }
    }
}
