//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RecommendItEntities : DbContext
    {
        public RecommendItEntities()
            : base("name=RecommendItEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Denuncias> Denuncias { get; set; }
        public virtual DbSet<DenunciasRecomendaciones> DenunciasRecomendaciones { get; set; }
        public virtual DbSet<DenunciasSolicitudRecomendaciones> DenunciasSolicitudRecomendaciones { get; set; }
        public virtual DbSet<DenunciasSolicitudValoraciones> DenunciasSolicitudValoraciones { get; set; }
        public virtual DbSet<DenunciasValoraciones> DenunciasValoraciones { get; set; }
        public virtual DbSet<Productos> Productos { get; set; }
        public virtual DbSet<Recomendaciones> Recomendaciones { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<SolicitudRecomendaciones> SolicitudRecomendaciones { get; set; }
        public virtual DbSet<SolicitudValoraciones> SolicitudValoraciones { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<Valoraciones> Valoraciones { get; set; }
    }
}
