//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recomendaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recomendaciones()
        {
            this.DenunciasRecomendaciones = new HashSet<DenunciasRecomendaciones>();
        }
    
        public int id { get; set; }
        public string titulo { get; set; }
        public string contenido { get; set; }
        public int id_usuario { get; set; }
        public int id_solicitud_recomendacion { get; set; }
        public int me_gusta { get; set; }
        public bool eliminado { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DenunciasRecomendaciones> DenunciasRecomendaciones { get; set; }
        public virtual SolicitudRecomendaciones SolicitudRecomendaciones { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
