//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Respuestas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Respuestas()
        {
            this.DenunciasRespuestas = new HashSet<DenunciasRespuestas>();
            this.Tags = new HashSet<Tags>();
        }
    
        public int id { get; set; }
        public string contenido { get; set; }
        public int autor { get; set; }
        public int id_pregunta { get; set; }
        public int puntaje { get; set; }
        public bool eliminado { get; set; }
        public string imagen { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public bool denunciado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DenunciasRespuestas> DenunciasRespuestas { get; set; }
        public virtual Preguntas Preguntas { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tags> Tags { get; set; }
    }
}
