//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudValoraciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SolicitudValoraciones()
        {
            this.DenunciasSolicitudValoraciones = new HashSet<DenunciasSolicitudValoraciones>();
            this.Valoraciones = new HashSet<Valoraciones>();
        }
    
        public int id { get; set; }
        public string titulo { get; set; }
        public string leyenda { get; set; }
        public int id_usuario { get; set; }
        public Nullable<int> visitas { get; set; }
        public bool eliminado { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string foto { get; set; }
        public int cant_recomendaciones { get; set; }
        public int reputacion_otorgada { get; set; }
        public bool sin_skill { get; set; }
        public bool skill_prisa { get; set; }
        public bool skill_destacado { get; set; }
        public Nullable<int> nivel_requerido { get; set; }
        public int id_producto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DenunciasSolicitudValoraciones> DenunciasSolicitudValoraciones { get; set; }
        public virtual Productos Productos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Valoraciones> Valoraciones { get; set; }
    }
}
