//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.DenunciasRecomendaciones = new HashSet<DenunciasRecomendaciones>();
            this.DenunciasSolicitudRecomendaciones = new HashSet<DenunciasSolicitudRecomendaciones>();
            this.DenunciasSolicitudValoraciones = new HashSet<DenunciasSolicitudValoraciones>();
            this.DenunciasValoraciones = new HashSet<DenunciasValoraciones>();
            this.Recomendaciones = new HashSet<Recomendaciones>();
            this.SolicitudRecomendaciones = new HashSet<SolicitudRecomendaciones>();
            this.SolicitudValoraciones = new HashSet<SolicitudValoraciones>();
            this.Valoraciones = new HashSet<Valoraciones>();
        }
    
        public int id { get; set; }
        public string email { get; set; }
        public string nombre_usuario { get; set; }
        public string contrasena { get; set; }
        public string apellido { get; set; }
        public string nombre { get; set; }
        public int id_rol { get; set; }
        public string pais { get; set; }
        public string localidad { get; set; }
        public int reputacion { get; set; }
        public decimal efectividad { get; set; }
        public int nivel { get; set; }
        public string foto { get; set; }
        public bool eliminado { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public string descripcion { get; set; }
        public Nullable<bool> es_primera_vez { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DenunciasRecomendaciones> DenunciasRecomendaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DenunciasSolicitudRecomendaciones> DenunciasSolicitudRecomendaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DenunciasSolicitudValoraciones> DenunciasSolicitudValoraciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DenunciasValoraciones> DenunciasValoraciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recomendaciones> Recomendaciones { get; set; }
        public virtual Roles Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitudRecomendaciones> SolicitudRecomendaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitudValoraciones> SolicitudValoraciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Valoraciones> Valoraciones { get; set; }
    }
}
